baseURL = "https://hungry-benz-1fa7b3.netlify.com/"
languageCode = "en-us"
title = "The Mendercap Missives"
theme = "hugo-tufte"

[params]
  copyrightHolder = "Michael Chumak"
  subtitle = "A hobby blog by Mendercap and friends"